### ISSUE TITLE
Start Collapsed

### ISSUE THREAD

**Issue by jdc1898** [alexbowers/nova-categorise-resources#11]
Is there a configuration option or way to set the default behavior to closed?

**Comment by alexbowers** [comment]
Currently, there is not. 

I am no longer maintaining this package since the main reason for its existance is no longer required as its built into core. 

I will take PRs if they are simple, other than that, perhaps put a suggestion to the core Nova team to make resource groups collapsable.

**Comment by daugaard47** [comment]
@alexbowers You say that this functionality is built into Nova core. I'm on Nova 3+ now and do not see how to added this collapsible functionality. Yes you can use `public static $group = 'My Category';` but the categories do not collapse. I have a large site and the sidebar is out of control.
If this is possible in Nova core now, could you point me in the right direction?

**Comment by alexbowers** [comment]
Sorry I havent used nova in quite a long time, its possible it isn't in nova now, or that it was never collapsable.

Feel free to fork this project to provide yourself with the functionality you need, but unfortunately, since I dont use Nova anymore and haven't since 2.x I wouldn't be able to guide you appropriately to the right files.
